trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'macos-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
    checkLatest: true

- script: npm install -g cordova
  displayName: 'Install Cordova'

- script: npm install
  displayName: 'Install dependencies'

- script: |
    cordova platform add ios
    cordova prepare ios
    cd platforms/ios
    pod install
    cd ../..
    cordova build ios
  displayName: 'Build iOS App'
