name: MuiX
branch:
  master:
    ci: true
    tasks:
      - bash: |
          npm install
          cordova prepare ios
          pod install --project-directory=platforms/ios
          cordova build ios
