name: iOS Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Install Cordova
        run: npm install -g cordova

      - name: Prepare iOS Platform
        run: cordova platform add ios

      - name: Build iOS
        run: |
          cordova prepare ios
          cd platforms/ios
          pod install
          cd ../..
          cordova build ios
